"""create configuracion table

Revision ID: 4ca9c1326d7c
Revises: 7c2c2e28c972
Create Date: 2026-05-18 06:22:20.831596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ca9c1326d7c'
down_revision: Union[str, Sequence[str], None] = '7c2c2e28c972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_index(op.f('ix_detalle_pedido_pedido_id'), table_name='detalle_pedido')
    op.drop_index(op.f('ix_detalle_pedido_producto_id'), table_name='detalle_pedido')
    op.drop_index(op.f('ix_direccion_entrega_usuario_id'), table_name='direccion_entrega')
    op.drop_index(op.f('ix_historial_estado_pedido_estado_desde'), table_name='historial_estado_pedido')
    op.drop_index(op.f('ix_historial_estado_pedido_estado_hasta'), table_name='historial_estado_pedido')
    op.drop_index(op.f('ix_historial_estado_pedido_pedido_id'), table_name='historial_estado_pedido')
    op.drop_index(op.f('ix_historial_estado_pedido_usuario_id'), table_name='historial_estado_pedido')
    op.drop_index(op.f('ix_pedido_direccion_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_estado_codigo'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_forma_pago_codigo'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_usuario_id'), table_name='pedido')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pedido_usuario_id'), 'pedido', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_pedido_forma_pago_codigo'), 'pedido', ['forma_pago_codigo'], unique=False)
    op.create_index(op.f('ix_pedido_estado_codigo'), 'pedido', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_pedido_direccion_id'), 'pedido', ['direccion_id'], unique=False)
    op.create_index(op.f('ix_historial_estado_pedido_usuario_id'), 'historial_estado_pedido', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_historial_estado_pedido_pedido_id'), 'historial_estado_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_historial_estado_pedido_estado_hasta'), 'historial_estado_pedido', ['estado_hasta'], unique=False)
    op.create_index(op.f('ix_historial_estado_pedido_estado_desde'), 'historial_estado_pedido', ['estado_desde'], unique=False)
    op.create_index(op.f('ix_direccion_entrega_usuario_id'), 'direccion_entrega', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_detalle_pedido_producto_id'), 'detalle_pedido', ['producto_id'], unique=False)
    op.create_index(op.f('ix_detalle_pedido_pedido_id'), 'detalle_pedido', ['pedido_id'], unique=False)
    op.drop_table('configuracion')
    # ### end Alembic commands ###
