"""add_pedidos_and_direcciones_tables

Revision ID: 7c2c2e28c972
Revises: d40a21c613ed
Create Date: 2026-05-18 02:48:21.189950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c2c2e28c972'
down_revision: Union[str, Sequence[str], None] = 'd40a21c613ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direccion_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('calle', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('piso_depto', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pago_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('direccion_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion_entrega.id'], ),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estadopedido.codigo'], ),
    sa.ForeignKeyConstraint(['forma_pago_codigo'], ['formapago.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('detalle_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('nombre_snapshot', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('precio_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('personalizacion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('historial_estado_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_desde', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('estado_hasta', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estado_desde'], ['estadopedido.codigo'], ),
    sa.ForeignKeyConstraint(['estado_hasta'], ['estadopedido.codigo'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('external_reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('pedido_id')
    )

    # Indices manuales para columnas de clave externa (FK)
    op.create_index(op.f('ix_direccion_entrega_usuario_id'), 'direccion_entrega', ['usuario_id'], unique=False)
    
    op.create_index(op.f('ix_pedido_usuario_id'), 'pedido', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_pedido_direccion_id'), 'pedido', ['direccion_id'], unique=False)
    op.create_index(op.f('ix_pedido_estado_codigo'), 'pedido', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_pedido_forma_pago_codigo'), 'pedido', ['forma_pago_codigo'], unique=False)
    
    op.create_index(op.f('ix_detalle_pedido_pedido_id'), 'detalle_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_detalle_pedido_producto_id'), 'detalle_pedido', ['producto_id'], unique=False)
    
    op.create_index(op.f('ix_historial_estado_pedido_pedido_id'), 'historial_estado_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_historial_estado_pedido_usuario_id'), 'historial_estado_pedido', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_historial_estado_pedido_estado_desde'), 'historial_estado_pedido', ['estado_desde'], unique=False)
    op.create_index(op.f('ix_historial_estado_pedido_estado_hasta'), 'historial_estado_pedido', ['estado_hasta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_estado_pedido_estado_hasta'), table_name='historial_estado_pedido')
    op.drop_index(op.f('ix_historial_estado_pedido_estado_desde'), table_name='historial_estado_pedido')
    op.drop_index(op.f('ix_historial_estado_pedido_usuario_id'), table_name='historial_estado_pedido')
    op.drop_index(op.f('ix_historial_estado_pedido_pedido_id'), table_name='historial_estado_pedido')
    
    op.drop_index(op.f('ix_detalle_pedido_producto_id'), table_name='detalle_pedido')
    op.drop_index(op.f('ix_detalle_pedido_pedido_id'), table_name='detalle_pedido')
    
    op.drop_index(op.f('ix_pedido_forma_pago_codigo'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_estado_codigo'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_direccion_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_usuario_id'), table_name='pedido')
    
    op.drop_index(op.f('ix_direccion_entrega_usuario_id'), table_name='direccion_entrega')

    op.drop_table('pago')
    op.drop_table('historial_estado_pedido')
    op.drop_table('detalle_pedido')
    op.drop_table('pedido')
    op.drop_table('direccion_entrega')
    # ### end Alembic commands ###
