"""add_notas_to_pedido

Revision ID: f6da0538ac37
Revises: 4ca9c1326d7c
Create Date: 2026-05-20 20:18:29.715949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6da0538ac37'
down_revision: Union[str, Sequence[str], None] = '4ca9c1326d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('notas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'notas')
    # ### end Alembic commands ###
